version: "3"

services:
  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: wedding-backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app 
    environment:
      - PYTHONPATH=/app  
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload  # ✅ 자동 리로딩

volumes:
  mysql_data: