version: "3"

services:
  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wedding_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: wedding-backend  # `build` 아래가 아니라 `backend`의 속성으로 위치
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  mysql_data: